function days = get_learning_days()

days = [... 
    hwwa.get_hitch_learning_days() ...
  , hwwa.get_tarantino_learning_days() ...
  , hwwa.get_ephron_learning_days() ...
];

days = unique( days );

end