inputs = hwwa.get_common_make_defaults();

inputs.config.PATHS.data_root = '/Users/Nick/Desktop/test_data_root2';

hwwa.make_unified( inputs );
hwwa.make_edfs( inputs );
hwwa.make_events( inputs );
hwwa.make_el_events( inputs );
hwwa.make_alternate_el_events( inputs );
hwwa.make_labels( inputs );

res = hwwa.make_edf_trials( inputs ...
  , 'event',        {'go_target_onset', 'go_target_acquired'} ...
  , 'event_subdir', 'edf_events' ...
  , 'look_back',    0 ...
  , 'look_ahead',   1000 ...
  , 'overwrite',    true ...
  , 'append',       true ...
  , 'keep_output',  true ...
);