function hwwa_run_plot_drug_behav(varargin)

defaults = hwwa.get_common_make_defaults();
params = hwwa.parsestruct( defaults, varargin );

behav_outputs = hwwa_load_basic_behav_measures( ...
    'config', params.config ...
  , 'trial_bin_size', 50 ...
  , 'trial_step_size', 1 ...
  , 'is_parallel', true ...
);

hwwa_plot_drug_behav( behav_outputs.rt, behav_outputs.labels' );

end