function outs = hwwa_load_approach_avoid_behavior(varargin)

outs = hwwa_load_basic_behav_measures( ...
    'files_containing', hwwa.approach_avoid_files() ...
  , 'trial_bin_size', 50 ...
  , 'trial_step_size', 50 ...
  , 'is_parallel', true ...
  , 'error_handler', 'error' ...
  , 'num_run_time_quantiles', 10 ...
  , varargin{:} ...
);

end