function outs = hwwa_approach_avoid_go_target_aligned(varargin)

outs = hwwa_load_edf_aligned( ...
    'start_event_name', 'go_target_onset' ...
  , 'stop_event_name', 'go_target_offset' ...
  , 'look_back', 0 ...
  , 'look_ahead', 0 ...
  , 'is_parallel', true ...
  , 'files_containing', hwwa.approach_avoid_files() ...
  , 'error_handler', 'error' ...
  , varargin{:} ...
);

end